version: '3'

services:
  book: 
    build: .
    volumes:
      - ./:/src/app
    depends_on: 
      - 'database'
    ports:
      - '3004:3004'
    restart: always
  database: 
    image: mongo:latest
    restart: always